### ISSUE TITLE
Add GKE support

### ISSUE THREAD

**Issue by tjtelan** [infinyon/k8-api#168]
If your kubeconfig includes a GKE cluster, the config parsing will fail due to this currently unsupported `auth_provider` block within the users.

```
 auth-provider:
      config:
        access-token: xxx
        cmd-args: config config-helper --format=json
        cmd-path: /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2022-05-10T00:11:22Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
```

Additionally, access is primarily dynamic token based, not cert based. So client requests need to be modified to identify when a token is not static and how to renew it.

For simplicity, I think it is a good enough start to assume `gcloud` is installed, and it was used to write cluster info into the config via `gcloud container clusters get-credentials`. This way we can use the `cmd-path` + `cmd-args` to do the token retrieval.
