### ISSUE TITLE
Unable to parse `"users[1].user.exec.args` null value.

### ISSUE THREAD

**Issue by gibbz00** [infinyon/k8-api#252]
I was able to fix this by manually editing the config `args: null`  to `args: []` for it to match https://github.com/infinyon/k8-api/blob/b5652f4df7afc6a38c04b3dd317d6849b335b4ba/src/k8-config/src/config.rs#L145

### fluvio cluster check
```
Current channel: stable
Running pre-startup checks...
Note: This may require admin access to current Kubernetes context
    ❌ Check Kubernetes config failed Unhandled K8 client error: K8 Error: SerdeError(
    Message(
        "invalid type: unit value, expected a sequence",
        Some(
            Pos {
                marker: Marker {
                    index: 12075,
                    line: 48,
                    col: 12,
                },
                path: "users[1].user.exec.args",
            },
        ),
    ),
)
    ❌ skipping check: Kubernetes version because required components are not met
    ✅ Supported helm version 3.12.0+gc9f554d is installed
    ❌ skipping check: Kubernetes Service Permission because required components are not met
    ❌ skipping check: Kubernetes Crd Permission because required components are not met
    ❌ skipping check: Kubernetes Service Account Permission because required components are not met
    ❌ skipping check: Fluvio Sys Chart because required components are not met
💔 Some pre-flight check failed!
Preflight check failed
```

### kubeconfig

Example of a context that exists in the config but which isn't necessarily being used for for fluvio.

```yaml
- name: gke_sublime_europe-north1-something
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
```
