### ISSUE TITLE
bug:  version API not set correctly for ownerReferences

### ISSUE THREAD

**Issue by sehz** [infinyon/k8-api#69]
related to: https://github.com/infinyon/fluvio/issues/1343.

Owner references is hard code to: `v1` instead from CRD:
```
ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: false
    kind: SpuGroup
    name: main
    uid: 62280ed2-4f01-46de-98d4-0cb133e5c49d
```
